# Generated by Django 2.2.1 on 2019-05-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
